version: "3.8"

services:
    app:
        container_name: inventory-api
        build: .
        ports:
            - "4000:4000"
        depends_on:
            - db
        env_file:
            - .env

    db:
        image: postgres:13
        container_name: postgres-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres321
            POSTGRES_DB: inventory-db
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
